# 워크플로우의 이름
name: Deploy to Server

# 워크플로우가 실행될 조건 설정
on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드를 체크아웃합니다.
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Docker Hub 로그인을 위한 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. Docker Hub에 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/togedaeng-backend:latest
          # ★★★ 핵심: build-args로 시크릿 값을 직접 전달 ★★★
          build-args: |
            FIREBASE_KEY_JSON=${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
