# 워크플로우의 이름
name: Deploy to Server

# 워크플로우가 실행될 조건 설정
on:
  push:
    branches:
      - dev  # dev 브랜치에 push 이벤트가 발생했을 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # 이 작업은 우분투 최신 버전 환경에서 실행됨

    steps:
      # 1. GitHub 레포지토리의 코드를 runner로 가져옴 (체크아웃)
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # ★★★ 수정된 부분 1: Base64 시크릿을 디코딩하여 파일 생성 ★★★
      # 이 단계가 먼저 실행되어야 Dockerfile이 파일을 찾을 수 있습니다.
      - name: Create Firebase Service Account Key file
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" | base64 --decode > ./src/main/resources/firebase-service-account.json

      # 4. Docker Hub 로그인을 위한 설정 (Docker Buildx)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 5. Docker Hub에 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ★★★ 수정된 부분 2: build-args 제거 ★★★
      # 6. Docker 이미지 빌드 및 Docker Hub에 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/togedaeng-backend:latest
