# 워크플로우의 이름
name: Deploy to Server

# 워크플로우가 실행될 조건 설정
on:
  push:
    branches:
      - dev  # dev 브랜치에 push 이벤트가 발생했을 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # 이 작업은 우분투 최신 버전 환경에서 실행됨

    steps:
      # 1. GitHub 레포지토리의 코드를 runner로 가져옴 (체크아웃)
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # ★★★★★ 가장 중요한 단계 ★★★★★
      # 3. GitHub Secrets에 저장된 값을 이용해 서비스 계정 키 파일을 생성
      # 이 단계가 있어야 Docker 빌드 시 파일을 찾을 수 있음
      - name: Create Firebase Service Account Key file
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > ./src/main/resources/firebase-service-account-key.json

      # 4. Docker Hub 로그인을 위한 설정 (Docker Buildx)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 5. Docker Hub에 로그인
      # GitHub Secrets에 DOCKER_USERNAME, DOCKER_PASSWORD를 미리 등록해야 함
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Docker 이미지 빌드 및 Docker Hub에 푸시
      # togedaeng-backend는 원하는 이미지 이름으로 변경 가능
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/togedaeng-backend:latest

      # 7. 서버에 접속하여 배포 스크립트 실행 (EC2 등)
      # 이 부분은 실제 배포 환경에 맞게 수정해야 합니다.
      # - name: Deploy to EC2
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USERNAME }}
      #     key: ${{ secrets.EC2_PRIVATE_KEY }}
      #     script: |
      #       docker pull ${{ secrets.DOCKER_USERNAME }}/togedaeng-backend:latest
      #       docker stop togedaeng-container || true
      #       docker rm togedaeng-container || true
      #       docker run -d -p 8080:8080 --name togedaeng-container ${{ secrets.DOCKER_USERNAME }}/togedaeng-backend:latest
